### ISSUE TITLE
希望可以加一个TG API 的参数

### ISSUE THREAD

**Issue by ridesnails** [qazxcdswe123/telegramMemoBot#10]
个人自建了tg api的反代，希望可以将
api.telegram.org 换成自建的api 网址
如：

官方api：

https://api.telegram.org/bot这里是机器人TOKEN/sendMessage?chat_id=这里是ChatID&text=推送的内容

饭袋api：

https://telegram_proxy.lulafun.workers.dev/botXXXXXX/sendMessage?chat_id=XXXXXX&text=XXXXX

**Comment by qazxcdswe123** [comment]
Done.

More test needed
