### ISSUE TITLE
支持图文的内容

### ISSUE THREAD

**Issue by monlor** [qazxcdswe123/telegramMemoBot#14]
默认像这样的图文内容，机器人不处理
<img width="612" alt="image" src="https://user-images.githubusercontent.com/20394007/236147605-5a541d37-470d-4300-b55d-8b687391827c.png">

**Comment by qazxcdswe123** [comment]
hi
这个是支持的
![image](https://user-images.githubusercontent.com/29861494/236187226-33876e86-e20e-4e5d-8531-813b0940249d.png)

**Comment by monlor** [comment]
<img width="992" alt="image" src="https://user-images.githubusercontent.com/20394007/236361268-ca6890f4-83e8-41cb-b864-bf5261ca3cb3.png">
我这里是报错这个，我服务器是美国的，按理说不可能访问失败

**Comment by WangBoee** [comment]
> <img alt="image" width="992" src="https://user-images.githubusercontent.com/20394007/236361268-ca6890f4-83e8-41cb-b864-bf5261ca3cb3.png">
> 
> 我这里是报错这个，我服务器是美国的，按理说不可能访问失败

应该是bot运行机制的问题，polling模式经常会这样，得偶尔重启一次容器。之前在别的项目中也有遇到类似情况，bot都是以polling模式运行。
![image](https://github.com/qazxcdswe123/telegramMemoBot/assets/29994612/34ff4546-6ea4-4bbc-9021-51d6668c6ccf)
