### ISSUE TITLE
Bot返回错误 Error: 

### ISSUE THREAD

**Issue by WangBoee** [qazxcdswe123/telegramMemoBot#16]
使用docker启动，这两天发现向bot发送任何消息都返回 `Error: `，vps上查看log显示以下内容：
```
2023-07-31 05:52:01,521 - root - ERROR - Error:  in send_text_memo
2023-07-31 05:52:01,530 - root - ERROR - Error:  in send_text_memo
2023-07-31 05:54:00,786 - root - ERROR - Error:  in send_text_memo
```

**Comment by qazxcdswe123** [comment]
估计是API变动了，现在memos已经内置了telegram bot，看了一下功能挺全的，可以考虑迁移过去，本项目估计不维护了：（

**Comment by WangBoee** [comment]
体验了memos内置的bot，不支持多用户，多账号收录到memos不太方便。感谢这个项目，使用体验很好，不维护太遗憾了。

**Comment by qazxcdswe123** [comment]
你指的多用户是多个Telegram帐号给同一个memos发信息吗，可以明确一下然后可能我去给memos那边提PR 🤣

**Comment by WangBoee** [comment]
> 你指的多用户是多个Telegram帐号给同一个memos发信息吗，可以明确一下然后可能我去给memos那边提PR 🤣

是的，多个tg账户向同一个memos发消息。如果能支持接收频道消息(bot已在频道里并有权限读信息)，也可以解决多用户对一个memos的情况。
