### ISSUE TITLE
更新到memos v0.9.1后Bot失效，显示 400 Bad Request

### ISSUE THREAD

**Issue by erbanku** [qazxcdswe123/telegramMemoBot#2]
### 如题和如图。

![image](https://user-images.githubusercontent.com/79493862/210163108-4f995f7e-65fe-4f0e-a07a-1d74bd8ddf16.png)

**Comment by qazxcdswe123** [comment]
Hi
无法复现此问题，可以考虑检查config内容，或者通过其他方式访问API测试。

**Comment by erbanku** [comment]
换Memo官网Open API测试了一下，正常。
我重装了一下Memo，并重置了一下API，现在我的也正常了。
