### ISSUE TITLE
bot 中使用 # 不能自动创建 tag

### ISSUE THREAD

**Issue by JiapengLi** [qazxcdswe123/telegramMemoBot#4]
如下图，bot创建得 memo 不能自动生成左侧索引入口

![image](https://user-images.githubusercontent.com/3773923/212900267-da7a0b57-b6d5-48ce-a6f0-ceafd2de26f8.png)

**Comment by qazxcdswe123** [comment]
~~这个似乎是memos那边到问题，通过 API 添加的 tags 要从 tag suggestions 里面手动添加~~
发现了还需要手动从 API 那边添加 tag，找时间修复。

**Comment by qazxcdswe123** [comment]
fixed

**Comment by JiapengLi** [comment]
My fork https://github.com/JiapengLi/MemosBot/
